TM-5970-Client-Profile-Export
MetaPhase-Consulting/State-TalentMAP-API pull request #1026
Opened 2024-06-24 23:45 UTC by cagbakwu

[[ticket](https://metaphase.atlassian.net/browse/TM-5970)]

Will remove WIP once TM-API is back up on my local.

2024-07-01 17:20 UTC, M00staff commented on talentmap_api/fsbid/services/client.py
> +        smart_str(u"TED"),
maybe format the date, here?

<img width="230" alt="image" src="https://github.com/MetaPhase-Consulting/State-TalentMAP-API/assets/12723877/099c58ba-61b5-49c9-9b68-4ba530fbcae2">

2024-07-01 17:21 UTC, M00staff commented on talentmap_api/fsbid/services/client.py
> +        smart_str(u"Location (Org)"),
the ticket asks for a location code, as well as the location ... 

<img width="388" alt="image" src="https://github.com/MetaPhase-Consulting/State-TalentMAP-API/assets/12723877/29bc4044-26f5-44c3-a0c4-93d9cb830815">

i only see location.

<img width="192" alt="image" src="https://github.com/MetaPhase-Consulting/State-TalentMAP-API/assets/12723877/f98b3c91-8e0f-4abb-b832-2eaf9fba7443">

2024-07-01 17:23 UTC, M00staff commented
missing CDO name

<img width="509" alt="image" src="https://github.com/MetaPhase-Consulting/State-TalentMAP-API/assets/12723877/ffb37acb-9de4-4fc3-b282-0da25301250a">

2024-07-01 17:24 UTC, M00staff commented on talentmap_api/fsbid/services/client.py
> +        smart_str(u"Status"),
might wanna double check to make sure this field is wired up correctly in dev1 - its just coming up blank for me locally

<img width="74" alt="image" src="https://github.com/MetaPhase-Consulting/State-TalentMAP-API/assets/12723877/7a5ec122-eb35-4066-ba28-88ce1512b246">

2024-07-01 17:25 UTC, M00staff requested changes
few minor changes - missing stuff from the A/C's

2024-07-01 17:26 UTC, M00staff commented on talentmap_api/fsbid/services/client.py
>          smart_str(u"Skill"),
is there handling for multiple employee skill codes? 

its mentioned in the A/C's, but i dont know how that would work ... I didn't even know it was possible 🤷

<img width="431" alt="image" src="https://github.com/MetaPhase-Consulting/State-TalentMAP-API/assets/12723877/23292847-a221-4b46-ad58-22601f81dd08">

2024-07-02 00:51 UTC, cagbakwu commented on talentmap_api/fsbid/services/client.py
> +        smart_str(u"Status"),
@M00staff ah yea thats because the value isn't in our mock, but it is there in dev1. I verified it.

2024-07-02 00:53 UTC, cagbakwu commented on talentmap_api/fsbid/services/client.py
>          smart_str(u"Skill"),
@M00staff yea Just in case, I have it looping through the skill codes incase more than 1 is available.

2024-07-02 02:10 UTC, M00staff commented on talentmap_api/fsbid/services/client.py
> +        smart_str(u"TED"),
the TED is still being formatted weird?

<img width="188" alt="image" src="https://github.com/MetaPhase-Consulting/State-TalentMAP-API/assets/12723877/3d9bf35b-52d5-45bd-a78b-2baaf0ca8a7d">

2024-07-02 02:14 UTC, M00staff requested changes
TED is still being formatted weird

2024-07-02 02:16 UTC, M00staff commented on talentmap_api/fsbid/services/client.py
> +        smart_str(u"TED"),
i dont think you need the timestamp is what i mean, you can just show it as `yyyy/mm/dd`

2024-07-02 13:00 UTC, cagbakwu commented on talentmap_api/fsbid/services/client.py
> +        smart_str(u"TED"),
@M00staff ah yea ok that makes sense. I removed it and should be good to go.

2024-07-02 13:02 UTC, cagbakwu commented
Should be good to go now 🫡

2024-07-02 15:03 UTC, M00staff approved these changes

2024-07-02 15:08 UTC, merged