TM-4844-CDO-API
MetaPhase-Consulting/State-TalentMAP-API pull request #1056
Opened 2024-08-12 19:25 UTC by cagbakwu

Dual Merge: 
- [FE PR](https://github.com/MetaPhase-Consulting/State-TalentMAP/pull/3077)

[Ticket](https://metaphase.atlassian.net/browse/TM-4844)

2024-08-13 01:52 UTC, cagbakwu commented on talentmap_api/fsbid/services/client.py
> +        "PV_BSCC_ID_I":null,
ID was intentionally left as "null" per Bob.

2024-08-13 18:41 UTC, jlam-mpc requested changes
Eligible and cusp changes look good on the API side, I'm not seeing it in the filter options but that might be a UI concern for myself.

Just have some questions on the update client functions

2024-08-13 18:41 UTC, jlam-mpc commented on talentmap_api/fsbid/services/client.py
> +        "package_name": 'Pkg_Wrap_dev',
Should this be `PKG_WEBAPI_WRAP_SPRINT99` instead?

2024-08-13 18:41 UTC, jlam-mpc commented on talentmap_api/fsbid/services/client.py
> +        "proc_name": 'prc_mod_alt_email_bscc',
Super confused because the spreadsheet says `prc_mod_alt_email` and a different payload but wanted to make sure all of the disparities were communicated on an email chain or something.

2024-08-13 18:41 UTC, jlam-mpc commented on talentmap_api/fsbid/services/client.py
> +        "PQRY_ERROR_DATA_O":"",
These two lines can typically be removed from a request mapping since they're actually for the return mapping instead and WS tend to supply us all of these together

2024-08-13 19:24 UTC, cagbakwu commented on talentmap_api/fsbid/services/client.py
> +        "package_name": 'Pkg_Wrap_dev',
@jlam-mpc this is the link for now that Bob created to combine the email and comments section. It will be changed later.

2024-08-13 19:25 UTC, cagbakwu commented on talentmap_api/fsbid/services/client.py
> +        "proc_name": 'prc_mod_alt_email_bscc',
@jlam-mpc yea sorry about that, bob created a whole new prc and package name for this and sent it through email because the initial one only covered emails but needed emails and comments to be combined.

2024-08-13 20:47 UTC, jlam-mpc requested changes

2024-08-13 20:47 UTC, jlam-mpc commented on talentmap_api/fsbid/services/client.py
> +        "PV_BSCC_ID_I":null,
Forgot to note this needs to say None for python files

2024-08-14 13:22 UTC, jlam-mpc approved these changes

2024-08-14 19:33 UTC, merged