Tm 6488 add eltoml
MetaPhase-Consulting/State-TalentMAP-API pull request #1084
Opened 2024-10-03 15:26 UTC by mansi-mp-200

Dual Merge
- [FE PR](https://github.com/MetaPhase-Consulting/State-TalentMAP/pull/3111)

[Ticket][(linkToTicket)](https://metaphase.atlassian.net/jira/software/c/projects/TM/boards/1?assignee=712020%3A3d9639a5-439c-4e2d-9bce-37b6924384d2&selectedIssue=TM-6488)

Editing how data is send to the WS BackOfficeCRUD endpoint in order to make updates to an EL position. These changes are made in fsbid/services/positions.py edit_el_positions() endpoint. 

Some other minor changes made such as changing the value we pick up for position number as well as changing what is passed in for data argument in edit_el_positions method call.

2024-10-03 15:36 UTC, fimbriano requested changes

2024-10-03 15:36 UTC, fimbriano commented on talentmap_api/fsbid/services/positions.py
> -    # Web Service JSON Input for EL Position edit
should we add this comment back? just for documentation haha

2024-10-03 15:36 UTC, fimbriano commented on talentmap_api/fsbid/views/positions.py
> +        # result = services.edit_el_positions(data=request.data, jwt_token=jwt) - original
lets remove the comments out parts, and i wonder if we actually need this formatted string -- im going to test this without the formatted string

2024-10-04 13:05 UTC, fimbriano approved these changes

2024-10-04 16:49 UTC, jlam-mpc approved these changes

2024-10-04 17:37 UTC, fimbriano commented on talentmap_api/fsbid/services/positions.py
> +            'positionNumber': x.get('POS_NUM_TEXT'),
that's how we feel too! we left positionNumber, because i wasn't planning on updating the UI (as that's how it was named previously), but any new keys we've been matching what the endpoint returns.

i'd love to start doing maintenance to rename the keys to match haha

2024-10-04 17:59 UTC, merged