Tm 6873 tm1 xml attachment
MetaPhase-Consulting/State-TalentMAP-API pull request #1123
Opened 2024-12-20 21:03 UTC by mansi-mp-200

[Ticket](https://metaphase.atlassian.net/jira/software/c/projects/TM/boards/1?assignee=712020%3A3d9639a5-439c-4e2d-9bce-37b6924384d2&selectedIssue=TM-6873)

Adding logger statements for debugging purposes for send_smtp_email function for TM1. This is to be added into dev alongside jeanie's work for demonstration purposes

2024-12-20 21:07 UTC, jlam-mpc approved these changes

2024-12-26 17:37 UTC, fimbriano requested changes

2024-12-26 17:37 UTC, fimbriano commented on talentmap_api/fsbid/services/tmone.py
> +from email.mime.text import MIMEText
```suggestion
```
duplicate import

2024-12-26 17:39 UTC, mansi-mp-200 commented on talentmap_api/fsbid/services/tmone.py
> +from email.mime.text import MIMEText
thank you for catching that :)

2024-12-26 17:42 UTC, fimbriano approved these changes

2024-12-26 19:15 UTC, closed without merging