Add new model for ranking bidders for a cycle position
MetaPhase-Consulting/State-TalentMAP-API pull request #425
Opened 2020-10-01 17:43 UTC by mjoyce91

Make sure to `build`

2020-10-14 15:57 UTC, scott062 commented on talentmap_api/available_positions/views/available_position.py
> -        return Response(aps)
Did you mean to delete this?

2020-10-14 16:38 UTC, mjoyce91 commented on talentmap_api/available_positions/views/available_position.py
> -        return Response(aps)
Probably not, good find. I'll take a look

2020-10-16 13:03 UTC, mjoyce91 commented on talentmap_api/available_positions/views/available_position.py
> +
Will do

2020-10-20 19:50 UTC, mjoyce91 commented on talentmap_api/available_positions/views/available_position.py
> +
@scott062 I don't think I have anything to add here? Everything we need is already in Swagger. I think because I used `GenericViewSet` we get it by default

2020-10-22 15:53 UTC, scott062 commented
![image](https://user-images.githubusercontent.com/38047685/96897953-23cbb980-145d-11eb-860e-01c8b264ae3d.png)
I was able to insert the same ranking for different perdets on the same position from swagger.

2020-10-22 17:09 UTC, scott062 commented
The delete removes all rankings for the signed-on user on a particular cp id. Do we need to capture more edge cases here? 

- Remove ALL rankings for signed-on user on cp_id (current)
- Remove SINGLE ranking for particular bidder (Removing from short list)
- Update ranking for a particular bidder (#1 -> #2) 
- Unranking an individual bidder without removing them (#1 -> Unranked - still on shortlist)

Maybe add a default unranked value for all of them? I don't know if there was a design decision about that, but it prevents an auto ranking that may be misleading to the users when they added to shortlist without having manually ranked anyone yet.

2020-10-22 17:11 UTC, scott062 requested changes
Just a couple questions - maybe outside the scope of v1.

2020-10-22 17:13 UTC, mjoyce91 commented
@scott062 yeah, all rules we might want at some point, but the requirements right now are so vague that I'm not going to get too deep with this right now.

2020-10-23 14:19 UTC, scott062 requested changes

2020-10-23 14:19 UTC, scott062 commented on talentmap_api/available_positions/models.py
> +        unique_together = (('user', 'cp_id', 'rank', 'bidder_perdet'))
This should be constraining my duplicate inserts - but its not. Syntax maybe?

2020-10-26 13:22 UTC, mjoyce91 commented on talentmap_api/available_positions/models.py
> +        unique_together = (('user', 'cp_id', 'rank', 'bidder_perdet'))
Might have an extra set of parens

2020-10-27 14:29 UTC, mjoyce91 commented on talentmap_api/available_positions/models.py
> +        unique_together = (('user', 'cp_id', 'rank', 'bidder_perdet'))
@scott062 try this again

2020-10-27 16:42 UTC, scott062 commented on talentmap_api/available_positions/models.py
> +        unique_together = (('user', 'cp_id', 'rank', 'bidder_perdet'))
Its working! Just note that you may want to break this into two different unique constraints
`unique_together = (('user', 'cp_id', 'rank'), ('user', 'cp_id', 'bidder_perdet'))`

2020-10-27 16:43 UTC, scott062 approved these changes
🔢  👍

2020-10-28 14:47 UTC, merged