Use case-insensitive ordering for saved searches
MetaPhase-Consulting/State-TalentMAP-API pull request #448
Opened 2020-11-30 20:50 UTC by mjoyce91

2020-12-03 13:15 UTC, elizabeth-jimenez commented on talentmap_api/user_profile/views/searches.py
> +    ordering_case_insensitive_fields = ("name") # put here only case insensitive fields
This does actually work for Z-A ordering, we would just have to be explicit about it in `ordering_case_insensitive_fields`

2020-12-03 13:18 UTC, elizabeth-jimenez commented on talentmap_api/common/filters.py
> +
`        for k in insensitive_ordering:
            if not k.startswith('-'):
                l = '-' + k
                if l not in insensitive_ordering:
                    insensitive_ordering.append(l)
`

we could add this so that `-ABC` is also taken into account when we want case-insensitive for 'ABC', would just have to also change `ordering_case_insensitive_fields = ("name")` to `ordering_case_insensitive_fields = ["name"]`

I'm not great at Python, so this may be completely not best practice 🤪

2020-12-03 13:20 UTC, elizabeth-jimenez commented on talentmap_api/common/filters.py
> +class CaseInsensitiveOrderingFilter(restFilters.OrderingFilter):
❤️

2020-12-03 18:44 UTC, elizabeth-jimenez requested changes
Not necessary, as this PR does fix it, but see comments

2020-12-04 14:54 UTC, mjoyce91 commented on talentmap_api/common/filters.py
> +
Can you expand on this?

2020-12-04 18:40 UTC, mjoyce91 commented on talentmap_api/common/filters.py
> +
Updated! Good fine 👍

2020-12-04 19:12 UTC, elizabeth-jimenez approved these changes
🍰 🧁  🍬 🥮 👍

2020-12-07 20:25 UTC, merged