add remarks to aih & pma export TM-4136
MetaPhase-Consulting/State-TalentMAP-API pull request #774
Opened 2023-03-16 00:34 UTC by SidelineCory24

To-do:
- [ ] Add remarks to AIH export
- [ ] Add remarks to PMA export

2023-03-16 13:47 UTC, elizabeth-jimenez commented on talentmap_api/fsbid/services/common.py
> +            if x == 'remarks[0].remarkRefData':
this function should remain generic - checkout how `csv_fsbid_template_to_tm` is used in other places to handle data it wants to transform

2023-03-16 13:49 UTC, elizabeth-jimenez commented on talentmap_api/fsbid/services/agenda.py
> +            'remarks[0].remarkRefData': [],
check the documentation (commented out above function) for the function to dbl check this

2023-03-16 16:24 UTC, SidelineCory24 commented on talentmap_api/fsbid/services/agenda.py
> +            'remarks[0].remarkRefData': [],
update made

2023-03-16 18:35 UTC, elizabeth-jimenez commented on talentmap_api/fsbid/services/common.py
> +        remarksData = pydash.join(remarksData, '; ')
Since this is our 2nd panel specific function, can we go ahead and throw this one and `panel_process_dates_csv` in a panel file?

2023-03-16 18:37 UTC, elizabeth-jimenez commented on talentmap_api/fsbid/services/common.py
> +        remarksData = pydash.join(remarksData, '; ')
although, this function has the potential to be used on other places, so maybe just rename it and move up above the `# Panel Helper Functions` comment

2023-03-16 18:58 UTC, elizabeth-jimenez commented on talentmap_api/fsbid/services/common.py
> +        remarksData = pydash.map_(parse_agenda_remarks(remarks), 'text')
you can chain your pydash methods: `pydash.chain(parse_agenda_remarks(remarks)).map_('text').join('; ').value()`

2023-03-16 18:59 UTC, elizabeth-jimenez requested changes
really just the renaming and moving of function

2023-03-16 19:00 UTC, elizabeth-jimenez commented on talentmap_api/fsbid/services/common.py
> +        remarksData = pydash.map_(parse_agenda_remarks(remarks), 'text')
not required tho

2023-03-16 19:26 UTC, SidelineCory24 commented on talentmap_api/fsbid/services/common.py
> +        remarksData = pydash.join(remarksData, '; ')
renamed and moved up

2023-03-16 19:30 UTC, SidelineCory24 commented on talentmap_api/fsbid/services/common.py
> +        remarksData = pydash.map_(parse_agenda_remarks(remarks), 'text')
didn't know this, nice! and updated

2023-03-16 19:41 UTC, SidelineCory24 commented
> really just the renaming and moving of function

changes pushed

2023-03-16 21:08 UTC, elizabeth-jimenez commented on talentmap_api/fsbid/services/common.py
> +            remarks = pydash.map_(pydash.get(record, "remarks", []), 'text')
so something i noticed, I think we'll only ever get the None Listed if our try fails, but it won't fail for no Remarks. So what we can do is add 
```
        finally:
            remarks = remarks or 'None listed'
```

2023-03-16 22:11 UTC, SidelineCory24 commented on talentmap_api/fsbid/services/common.py
> +            remarks = pydash.map_(pydash.get(record, "remarks", []), 'text')
done

2023-03-16 22:16 UTC, SidelineCory24 commented on talentmap_api/fsbid/services/common.py
> +            remarks = pydash.map_(pydash.get(record, "remarks", []), 'text')
double checked and panel meeting agendas will show none listed in the csv

2023-03-16 22:16 UTC, SidelineCory24 commented
@elizabeth-jimenez ready for re-review review

2023-03-17 12:39 UTC, elizabeth-jimenez approved these changes
🦋

2023-03-17 13:25 UTC, merged