[TM-5389] Projected Vacancy Integration (Edit)
MetaPhase-Consulting/State-TalentMAP-API pull request #936
Opened 2024-02-14 13:53 UTC by jlam-mpc

Dual Merge: 
- [FE PR](https://github.com/MetaPhase-Consulting/State-TalentMAP/pull/2861)
- [Mock PR](https://github.com/MetaPhase-Consulting/mock-fsbid/pull/437)

[TM-5389](https://metaphase.atlassian.net/browse/TM-5389)

2024-02-22 19:57 UTC, elizabeth-jimenez commented on talentmap_api/fsbid/views/admin_projected_vacancies.py
> +    def put(self, request):
for both metadata and langoffsets

2024-02-22 20:02 UTC, elizabeth-jimenez commented on talentmap_api/fsbid/urls/admin_projected_vacancies.py
> +    url(r'^language_offsets/$', views.FSBidAdminProjectedVacancyMetadataView.as_view(), name='admin-projected-vacancies-lang-offsets'),
same view
is L16 already captured on L10?

2024-02-23 14:58 UTC, elizabeth-jimenez commented on talentmap_api/fsbid/views/admin_projected_vacancies.py
> +        result = services.get_admin_projected_vacancy_lang_offsets(request.data, request.META['HTTP_JWT'])
```suggestion
        result = services.get_admin_projected_vacancy_lang_offsets(request.query_params, request.META['HTTP_JWT'])
```

2024-02-23 19:19 UTC, elizabeth-jimenez commented
`<LOT_SEQ_NUM>None Listed</LOT_SEQ_NUM>` looks like we may be passing None Listed to WS 😅

2024-02-23 19:26 UTC, elizabeth-jimenez requested changes
1. `request.data` to `request.query_params` * 2
2. make sure not passing None Listed to WS

2024-02-28 14:45 UTC, scott062 commented on talentmap_api/fsbid/views/admin_projected_vacancies.py
> +
Not sure how legacy system handles editing capsules bc I thought they were unified under one editing proc - this may be duplicate to other edit capsule views from ppos - no change for now, just food for thought

2024-02-28 14:57 UTC, scott062 commented on talentmap_api/fsbid/views/admin_projected_vacancies.py
> +        return Response(result)
Without looking at the docs - may want to move this to reference in follow up ticket - unless language offsets are only for admin. Sometimes hard to tell if the ref data is specific to certain features or more widely applicable. For example, maintain asg may also use lang offsets (No changes for now)

2024-02-28 15:34 UTC, jlam-mpc commented on talentmap_api/fsbid/views/admin_projected_vacancies.py
> +        return Response(result)
So for this EP, it's getting the language offset selections for a particular PV. I feel like your comment is applicable to the `FSBidAdminProjectedVacancyLangOffsetOptionsView` and `FSBidAdminProjectedVacancyFiltersView` functions, however if you look at the payloads for them I feel as though they are too specific to admin PV to be moved to reference? We'd only move this to reference if it was globally used in TM right?

2024-02-28 15:46 UTC, scott062 commented on talentmap_api/fsbid/views/admin_projected_vacancies.py
> +        return Response(result)
Yea they hide ref data behind feature specific procs but they seem to call common procs behind the scenes - wonder if we can get those instead to be universally available for features as we need them

2024-02-28 15:48 UTC, elizabeth-jimenez approved these changes
Scott wants me to Approve bc he is the best

2024-02-28 16:24 UTC, merged