TM-6076: Publishable Positions Re-Integration (Read, Filtering, Pagination)
MetaPhase-Consulting/State-TalentMAP-API pull request #999
Opened 2024-05-22 18:37 UTC by pveland621

WIP while standing up PRs

ACs:
- Publishable Position Cards reading in all relevant fields
- Filters loading + filter requests look good
- Pagination/Total Results works as best we can test on local

Dual Merge: 
- [FE PR](linkToFrontEndPR)
- [Mock PR](linkToMockPR)

[Ticket](https://metaphase.atlassian.net/browse/TM-6076)

2024-05-28 11:53 UTC, jlam-mpc requested changes

2024-05-28 11:53 UTC, jlam-mpc commented on talentmap_api/fsbid/services/publishable_positions.py
> +    }
This follows up on my comment in the mockfsbid PR but this looks good, I'm just unsure if you need to first extract the array from a "data" field in the return first or not.

2024-05-28 11:57 UTC, jlam-mpc commented on talentmap_api/fsbid/services/publishable_positions.py
> +    }
I also almost want to recommend returning every field from FSBID just in case.

2024-05-28 11:59 UTC, jlam-mpc commented on talentmap_api/fsbid/services/publishable_positions.py
> +        'grade': data.get('posgradecode'),
Should bureau, status, payPlan, and grade also use the format desc code utility?

2024-05-30 12:57 UTC, pveland621 commented on talentmap_api/fsbid/services/publishable_positions.py
> +        'combined_pp_grade': combine_pp_grade(data.get('pospayplancode'), data.get('posgradecode')),
done

2024-06-03 17:16 UTC, jlam-mpc commented on talentmap_api/fsbid/services/publishable_positions.py
> +    }
Patrick, you could also just do 

```
    return {
        ** data,
        'combinedPPGrade': combine_pp_grade(data.get('pospayplancode'), data.get('posgradecode')),
        // Add any other custom fields you need to covnert here
    }
```

2024-06-03 18:25 UTC, pveland621 commented on talentmap_api/fsbid/services/publishable_positions.py
> +        'grade': data.get('posgradecode'),
probably, and it would take 2 seconds to implement but im not seeing an up to date mockup so i'm inclined to just leave it as is for now

2024-06-04 20:15 UTC, elizabeth-jimenez commented on talentmap_api/settings.py
> -PUBLISHABLE_POSITIONS_API_URL = get_delineated_environment_variable('PUBLISHABLE_POSITIONS_API_URL', 'http://mock_fsbid:3333/v1/publishablePositions')
![image](https://github.com/MetaPhase-Consulting/State-TalentMAP-API/assets/23065001/bc23b90b-4db1-4117-94b0-c756e0e5a2d9)
do we no longer need the `/v1/publishablePositions`?

2024-06-04 20:16 UTC, elizabeth-jimenez commented on talentmap_api/settings.py
> -PUBLISHABLE_POSITIONS_API_URL = get_delineated_environment_variable('PUBLISHABLE_POSITIONS_API_URL', 'http://mock_fsbid:3333/v1/publishablePositions')
^ in mock

2024-06-05 15:22 UTC, pveland621 commented on talentmap_api/settings.py
> -PUBLISHABLE_POSITIONS_API_URL = get_delineated_environment_variable('PUBLISHABLE_POSITIONS_API_URL', 'http://mock_fsbid:3333/v1/publishablePositions')
no i dont believe so, but there are a couple places like for capsule descriptions that use the root so that would be a 2 second change

2024-06-10 18:49 UTC, elizabeth-jimenez commented on talentmap_api/fsbid/services/publishable_positions.py
> +        'skill': services.format_desc_code(data.get('posskilldesc'), data.get('posskillcode')),
🥲

2024-06-10 19:15 UTC, elizabeth-jimenez commented on talentmap_api/fsbid/services/common.py
> +    if api_root is 'http://mock_fsbid:3333/v2/publishablePositions':
rip

2024-06-10 19:15 UTC, elizabeth-jimenez commented on talentmap_api/common/common_helpers.py
> +def format_dates(input_date):
borrowed Moose's function from bid audit

2024-06-10 20:34 UTC, merged